### ISSUE TITLE
NFS Requiring Installation

### ISSUE THREAD

**Issue by ausernameliam** [JH-Laboratory/DosGameLauncher#1]
NFS requires installation. When trying to install to the directory it suggests, the installation fails.
![image](https://user-images.githubusercontent.com/80932372/111720982-3b487c00-881c-11eb-8e0a-02cfb6ab2168.png)

**Comment by JHunter09** [comment]
### Due to issues we can't work around, Need For Speed has been removed from the launcher.
---
###### Thank you for your contribution. -J.Hunter
