### ISSUE TITLE
DN3D Doesn't Launch

### ISSUE THREAD

**Issue by ausernameliam** [JH-Laboratory/DosGameLauncher#2]
DN3D opens DOSBox but doesn't try to launch the game itself.
![image](https://user-images.githubusercontent.com/80932372/111721058-60d58580-881c-11eb-9651-3d64dd7ddcd4.png)

**Comment by JHunter09** [comment]
Despite trying multiple times, I have failed to reproduce this issue. Can you attempt to replicate it yourself, and upload an image of the `duke3d` directory?
---
###### Thank you for your contribution. -J.Hunter

**Comment by JHunter09** [comment]
Disregard my last comment, it was an issue with the installer, and has been fixed.

---
###### Thank you for your contribution. -J.Hunter
