### ISSUE TITLE
Daggerfall Fails to Launch

### ISSUE THREAD

**Issue by ausernameliam** [JH-Laboratory/DosGameLauncher#3]
Daggerfall fails to launch, complaining that multiple files don't exist, and then saying drive C doesn't exist and must be mounted first.
![image](https://user-images.githubusercontent.com/80932372/111721192-a09c6d00-881c-11eb-9cc4-ad6fea11e456.png)

**Comment by JHunter09** [comment]
### Issue has been addressed, new config file has been written using runtime directory and paths.

---
###### Thank you for your contribution. -J.Hunter
