### ISSUE TITLE
Flight Sim Doesn't Launch

### ISSUE THREAD

**Issue by ausernameliam** [JH-Laboratory/DosGameLauncher#4]
Version 1.3.0 renamed Flight Sim 3 and now it doesn't launch from the launcher.
![image](https://user-images.githubusercontent.com/80932372/111746276-0b649d00-884b-11eb-9311-55e2cb796336.png)

**Comment by JHunter09** [comment]
Issue has been fixed as of 56082517c8c66e401556f147161d70d3b406ca22, was related to 954f044393437377a24cbb6cd750d3c3f0bcef73

---
###### Thank you for your contribution. -J.Hunter
